### PR TITLE
filter own tasks

### PR DESCRIPTION
**Pull request by maaaikoool**

### CODE REVIEW

**Comment by avengerpenguin** [comment]
Did you have a good reason to need to exclude the graph commands themselves from the graph since they are in fact valid commands and arguably worth documenting?

**Comment by maaaikoool** [comment]
I used gulp-graph to document and have a better understanding of my gulp build pipeline, and I feel having those commands in the graph only pollute the documentation since they are not part of my code and therefore should not be documented.

**Comment by steve-gray** [comment]
+1 on this. When you've got a reasonably deep tree of tasks, and then there's just this one task off to the side that's not connected to the rest - it feels a bit out of place.

**Comment by avengerpenguin** [comment]
When I did it, it was for documenting all available things to run for new team members and the graph command itself is indeed something you can run.

I think a way to tackle this is to make it configurable and there's a flag like hideSelf: true. Would that be acceptable?

**Comment by steve-gray** [comment]
That's pretty much what I meant :)

**Pull request merged**
